# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- master

#jobs:
#  - job: thisIsMyTestingJobOk
#    pool:
#      vmImage: "ubuntu-16.04"
#    steps:
#    - bash: echo "Hello from the great beyond yo!!!!"
#    - bash: pwd
#    - bash: ls

jobs:
  - job: building_the_test_application
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: 'dotnet/aspnet/webappWithTests/Application/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      AWS.AccessKeyID: $(AWS_ACCESS_KEY_ID)
      AWS.SecretAccessKey: $(AWS_SECRET_ACCESS_KEY) 

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    #- bash: "cd dotnet && cd aspnet && cd webappWithTests && cd Application && cd SampleWebApplication && ls"

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    #- bash: "cd dotnet && cd aspnet && cd webappWithTests && cd Application && cd SampleWebApplication && ls"
    #- task: VSTest@2
      #inputs:
        #platform: '$(buildPlatform)'
        #configuration: '$(buildConfiguration)'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: "dotnet/aspnet/webappWithTests/Application/SampleWebApplication/bin"
        includeRootFolder: false
        archiveType: "zip"
        archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.SourceVersion).zip"



    - bash: echo $(Build.SourceVersion)
    - bash: "ls $(Build.BinariesDirectory)"
    - bash: "ls $(Build.ArtifactStagingDirectory)"
    - task: PowerShell@2
      inputs:
        script: "Write-Host ls env:"
    #- task: S3Upload@1
      #inputs:
        #bucketName: 'bookenda-azure-builds-test'
        #regionName: us-east-1
        #targetFolder: "testinG"

